# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    ports:
      - "27017:27017"

    volumes:
      - mongodata:/data/db
#      - '../../../.mongo_data:/data/db/'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: admin
volumes:
  mongodata:
    driver: local